<?xml version="1.0" encoding="UTF-8"?>
<module external.linked.project.id=":Topics-Creating_custom_exceptions-Catch_custom_exception" external.linked.project.path="$MODULE_DIR$/../../../../../Topics/Creating custom exceptions/Catch custom exception" external.root.project.path="$MODULE_DIR$/../../../../.." external.system.id="GRADLE" external.system.module.group="Basic_Calculator" external.system.module.version="unspecified" type="JAVA_MODULE" version="4">
  <component name="FacetManager">
    <facet type="java-gradle" name="Java-Gradle">
      <configuration>
        <option name="BUILDABLE" value="false" />
      </configuration>
    </facet>
    <facet type="android-gradle" name="Android-Gradle">
      <configuration>
        <option name="GRADLE_PROJECT_PATH" value=":Topics-Creating_custom_exceptions-Catch_custom_exception" />
        <option name="LAST_SUCCESSFUL_SYNC_AGP_VERSION" />
        <option name="LAST_KNOWN_AGP_VERSION" />
      </configuration>
    </facet>
  </component>
  <component name="NewModuleRootManager">
    <output url="file://$MODULE_DIR$/../../../../../Topics/Creating custom exceptions/Catch custom exception/out/production/classes" />
    <output-test url="file://$MODULE_DIR$/../../../../../Topics/Creating custom exceptions/Catch custom exception/out/test/classes" />
    <exclude-output />
    <content url="file://$MODULE_DIR$/../../../../../Topics/Creating custom exceptions/Catch custom exception">
      <excludeFolder url="file://$MODULE_DIR$/../../../../../Topics/Creating custom exceptions/Catch custom exception/.gradle" />
      <excludeFolder url="file://$MODULE_DIR$/../../../../../Topics/Creating custom exceptions/Catch custom exception/build" />
      <excludeFolder url="file://$MODULE_DIR$/../../../../../Topics/Creating custom exceptions/Catch custom exception/out" />
    </content>
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
  </component>
</module>